import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderClient from "@/components/HeaderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <div className="max-w-5xl mx-auto flex items-center justify-between p-4">
            <a href="/" className="font-semibold">SocialConnect</a>
            <nav className="space-x-4 text-sm">
              <HeaderClient />
            </nav>
          </div>
        </header>
        <main className="max-w-5xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
